package entity;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transform.proto

public final class Transform {
  private Transform() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImageRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 width = 1;</code>
     * @return The width.
     */
    int getWidth();

    /**
     * <code>int32 height = 2;</code>
     * @return The height.
     */
    int getHeight();

    /**
     * <code>bytes image = 3;</code>
     * @return The image.
     */
    com.google.protobuf.ByteString getImage();

    /**
     * <code>int32 type = 4;</code>
     * @return The type.
     */
    int getType();
    /**
     * <code>int32 pixelBits = 5;</code>
     * @return The pixelBits.
     */
    int getPixelBits();
    /**
     * <code>int32 numComponents = 6;</code>
     * @return The numComponents.
     */
    int getNumComponents();

    /**
     * <code>int32 transparency = 7;</code>
     * @return The transparency.
     */
    int getTransparency();

    /**
     * <code>bool hasalpah = 8;</code>
     * @return The hasalpah.
     */
    boolean getHasalpah();

    /**
     * <code>bool isalphapre = 9;</code>
     * @return The isalphapre.
     */
    boolean getIsalphapre();
  }
  /**
   * <pre>
   * The request message containing the user's name.
   * </pre>
   *
   * Protobuf type {@code ImageRequest}
   */
  public static final class ImageRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImageRequest)
      ImageRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImageRequest.newBuilder() to construct.
    private ImageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImageRequest() {
      image_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ImageRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Transform.internal_static_ImageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Transform.internal_static_ImageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Transform.ImageRequest.class, Transform.ImageRequest.Builder.class);
    }

    public static final int WIDTH_FIELD_NUMBER = 1;
    private int width_;
    /**
     * <code>int32 width = 1;</code>
     * @return The width.
     */
    @java.lang.Override
    public int getWidth() {
      return width_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 2;
    private int height_;
    /**
     * <code>int32 height = 2;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }

    public static final int IMAGE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString image_;
    /**
     * <code>bytes image = 3;</code>
     * @return The image.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getImage() {
      return image_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>int32 type = 4;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int PIXELBITS_FIELD_NUMBER = 5;
    private int pixelBits_;
    /**
     * <code>int32 pixelBits = 5;</code>
     * @return The pixelBits.
     */
    @java.lang.Override
    public int getPixelBits() {
      return pixelBits_;
    }

    public static final int NUMCOMPONENTS_FIELD_NUMBER = 6;
    private int numComponents_;
    /**
     * <code>int32 numComponents = 6;</code>
     * @return The numComponents.
     */
    @java.lang.Override
    public int getNumComponents() {
      return numComponents_;
    }

    public static final int TRANSPARENCY_FIELD_NUMBER = 7;
    private int transparency_;
    /**
     * <code>int32 transparency = 7;</code>
     * @return The transparency.
     */
    @java.lang.Override
    public int getTransparency() {
      return transparency_;
    }

    public static final int HASALPAH_FIELD_NUMBER = 8;
    private boolean hasalpah_;
    /**
     * <code>bool hasalpah = 8;</code>
     * @return The hasalpah.
     */
    @java.lang.Override
    public boolean getHasalpah() {
      return hasalpah_;
    }

    public static final int ISALPHAPRE_FIELD_NUMBER = 9;
    private boolean isalphapre_;
    /**
     * <code>bool isalphapre = 9;</code>
     * @return The isalphapre.
     */
    @java.lang.Override
    public boolean getIsalphapre() {
      return isalphapre_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (width_ != 0) {
        output.writeInt32(1, width_);
      }
      if (height_ != 0) {
        output.writeInt32(2, height_);
      }
      if (!image_.isEmpty()) {
        output.writeBytes(3, image_);
      }
      if (type_ != 0) {
        output.writeInt32(4, type_);
      }
      if (pixelBits_ != 0) {
        output.writeInt32(5, pixelBits_);
      }
      if (numComponents_ != 0) {
        output.writeInt32(6, numComponents_);
      }
      if (transparency_ != 0) {
        output.writeInt32(7, transparency_);
      }
      if (hasalpah_ != false) {
        output.writeBool(8, hasalpah_);
      }
      if (isalphapre_ != false) {
        output.writeBool(9, isalphapre_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (width_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, width_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, height_);
      }
      if (!image_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, image_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      if (pixelBits_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, pixelBits_);
      }
      if (numComponents_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, numComponents_);
      }
      if (transparency_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, transparency_);
      }
      if (hasalpah_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, hasalpah_);
      }
      if (isalphapre_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, isalphapre_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Transform.ImageRequest)) {
        return super.equals(obj);
      }
      Transform.ImageRequest other = (Transform.ImageRequest) obj;

      if (getWidth()
          != other.getWidth()) return false;
      if (getHeight()
          != other.getHeight()) return false;
      if (!getImage()
          .equals(other.getImage())) return false;
      if (getType()
          != other.getType()) return false;
      if (getPixelBits()
          != other.getPixelBits()) return false;
      if (getNumComponents()
          != other.getNumComponents()) return false;
      if (getTransparency()
          != other.getTransparency()) return false;
      if (getHasalpah()
          != other.getHasalpah()) return false;
      if (getIsalphapre()
          != other.getIsalphapre()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + getWidth();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + PIXELBITS_FIELD_NUMBER;
      hash = (53 * hash) + getPixelBits();
      hash = (37 * hash) + NUMCOMPONENTS_FIELD_NUMBER;
      hash = (53 * hash) + getNumComponents();
      hash = (37 * hash) + TRANSPARENCY_FIELD_NUMBER;
      hash = (53 * hash) + getTransparency();
      hash = (37 * hash) + HASALPAH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasalpah());
      hash = (37 * hash) + ISALPHAPRE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsalphapre());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Transform.ImageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transform.ImageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transform.ImageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transform.ImageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transform.ImageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transform.ImageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transform.ImageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transform.ImageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Transform.ImageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Transform.ImageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Transform.ImageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transform.ImageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Transform.ImageRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message containing the user's name.
     * </pre>
     *
     * Protobuf type {@code ImageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImageRequest)
        Transform.ImageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Transform.internal_static_ImageRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Transform.internal_static_ImageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Transform.ImageRequest.class, Transform.ImageRequest.Builder.class);
      }

      // Construct using entity.Transform.ImageRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        width_ = 0;

        height_ = 0;

        image_ = com.google.protobuf.ByteString.EMPTY;

        type_ = 0;

        pixelBits_ = 0;

        numComponents_ = 0;

        transparency_ = 0;

        hasalpah_ = false;

        isalphapre_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Transform.internal_static_ImageRequest_descriptor;
      }

      @java.lang.Override
      public Transform.ImageRequest getDefaultInstanceForType() {
        return Transform.ImageRequest.getDefaultInstance();
      }

      @java.lang.Override
      public Transform.ImageRequest build() {
        Transform.ImageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Transform.ImageRequest buildPartial() {
        Transform.ImageRequest result = new Transform.ImageRequest(this);
        result.width_ = width_;
        result.height_ = height_;
        result.image_ = image_;
        result.type_ = type_;
        result.pixelBits_ = pixelBits_;
        result.numComponents_ = numComponents_;
        result.transparency_ = transparency_;
        result.hasalpah_ = hasalpah_;
        result.isalphapre_ = isalphapre_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Transform.ImageRequest) {
          return mergeFrom((Transform.ImageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Transform.ImageRequest other) {
        if (other == Transform.ImageRequest.getDefaultInstance()) return this;
        if (other.getWidth() != 0) {
          setWidth(other.getWidth());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        if (other.getImage() != com.google.protobuf.ByteString.EMPTY) {
          setImage(other.getImage());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getPixelBits() != 0) {
          setPixelBits(other.getPixelBits());
        }
        if (other.getNumComponents() != 0) {
          setNumComponents(other.getNumComponents());
        }
        if (other.getTransparency() != 0) {
          setTransparency(other.getTransparency());
        }
        if (other.getHasalpah() != false) {
          setHasalpah(other.getHasalpah());
        }
        if (other.getIsalphapre() != false) {
          setIsalphapre(other.getIsalphapre());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                width_ = input.readInt32();

                break;
              } // case 8
              case 16: {
                height_ = input.readInt32();

                break;
              } // case 16
              case 26: {
                image_ = input.readBytes();

                break;
              } // case 26
              case 32: {
                type_ = input.readInt32();

                break;
              } // case 32
              case 40: {
                pixelBits_ = input.readInt32();

                break;
              } // case 40
              case 48: {
                numComponents_ = input.readInt32();

                break;
              } // case 48
              case 56: {
                transparency_ = input.readInt32();

                break;
              } // case 56
              case 64: {
                hasalpah_ = input.readBool();

                break;
              } // case 64
              case 72: {
                isalphapre_ = input.readBool();

                break;
              } // case 72
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int width_ ;
      /**
       * <code>int32 width = 1;</code>
       * @return The width.
       */
      @java.lang.Override
      public int getWidth() {
        return width_;
      }
      /**
       * <code>int32 width = 1;</code>
       * @param value The width to set.
       * @return This builder for chaining.
       */
      public Builder setWidth(int value) {
        
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 width = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWidth() {
        
        width_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>int32 height = 2;</code>
       * @return The height.
       */
      @java.lang.Override
      public int getHeight() {
        return height_;
      }
      /**
       * <code>int32 height = 2;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 height = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString image_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes image = 3;</code>
       * @return The image.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getImage() {
        return image_;
      }
      /**
       * <code>bytes image = 3;</code>
       * @param value The image to set.
       * @return This builder for chaining.
       */
      public Builder setImage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        image_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes image = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearImage() {
        
        image_ = getDefaultInstance().getImage();
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 4;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 4;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int pixelBits_ ;
      /**
       * <code>int32 pixelBits = 5;</code>
       * @return The pixelBits.
       */
      @java.lang.Override
      public int getPixelBits() {
        return pixelBits_;
      }
      /**
       * <code>int32 pixelBits = 5;</code>
       * @param value The pixelBits to set.
       * @return This builder for chaining.
       */
      public Builder setPixelBits(int value) {
        
        pixelBits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pixelBits = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPixelBits() {
        
        pixelBits_ = 0;
        onChanged();
        return this;
      }

      private int numComponents_ ;
      /**
       * <code>int32 numComponents = 6;</code>
       * @return The numComponents.
       */
      @java.lang.Override
      public int getNumComponents() {
        return numComponents_;
      }
      /**
       * <code>int32 numComponents = 6;</code>
       * @param value The numComponents to set.
       * @return This builder for chaining.
       */
      public Builder setNumComponents(int value) {
        
        numComponents_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 numComponents = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumComponents() {
        
        numComponents_ = 0;
        onChanged();
        return this;
      }

      private int transparency_ ;
      /**
       * <code>int32 transparency = 7;</code>
       * @return The transparency.
       */
      @java.lang.Override
      public int getTransparency() {
        return transparency_;
      }
      /**
       * <code>int32 transparency = 7;</code>
       * @param value The transparency to set.
       * @return This builder for chaining.
       */
      public Builder setTransparency(int value) {
        
        transparency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 transparency = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransparency() {
        
        transparency_ = 0;
        onChanged();
        return this;
      }

      private boolean hasalpah_ ;
      /**
       * <code>bool hasalpah = 8;</code>
       * @return The hasalpah.
       */
      @java.lang.Override
      public boolean getHasalpah() {
        return hasalpah_;
      }
      /**
       * <code>bool hasalpah = 8;</code>
       * @param value The hasalpah to set.
       * @return This builder for chaining.
       */
      public Builder setHasalpah(boolean value) {
        
        hasalpah_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool hasalpah = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearHasalpah() {
        
        hasalpah_ = false;
        onChanged();
        return this;
      }

      private boolean isalphapre_ ;
      /**
       * <code>bool isalphapre = 9;</code>
       * @return The isalphapre.
       */
      @java.lang.Override
      public boolean getIsalphapre() {
        return isalphapre_;
      }
      /**
       * <code>bool isalphapre = 9;</code>
       * @param value The isalphapre to set.
       * @return This builder for chaining.
       */
      public Builder setIsalphapre(boolean value) {
        
        isalphapre_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isalphapre = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsalphapre() {
        
        isalphapre_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImageRequest)
    }

    // @@protoc_insertion_point(class_scope:ImageRequest)
    private static final Transform.ImageRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Transform.ImageRequest();
    }

    public static Transform.ImageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImageRequest>
        PARSER = new com.google.protobuf.AbstractParser<ImageRequest>() {
      @java.lang.Override
      public ImageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ImageRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImageRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Transform.ImageRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ImageReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImageReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * The response message containing the greetings
   * </pre>
   *
   * Protobuf type {@code ImageReply}
   */
  public static final class ImageReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImageReply)
      ImageReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImageReply.newBuilder() to construct.
    private ImageReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImageReply() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ImageReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Transform.internal_static_ImageReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Transform.internal_static_ImageReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Transform.ImageReply.class, Transform.ImageReply.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Transform.ImageReply)) {
        return super.equals(obj);
      }
      Transform.ImageReply other = (Transform.ImageReply) obj;

      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Transform.ImageReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transform.ImageReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transform.ImageReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transform.ImageReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transform.ImageReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transform.ImageReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transform.ImageReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transform.ImageReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Transform.ImageReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Transform.ImageReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Transform.ImageReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transform.ImageReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Transform.ImageReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The response message containing the greetings
     * </pre>
     *
     * Protobuf type {@code ImageReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImageReply)
        Transform.ImageReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Transform.internal_static_ImageReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Transform.internal_static_ImageReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Transform.ImageReply.class, Transform.ImageReply.Builder.class);
      }

      // Construct using entity.Transform.ImageReply.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Transform.internal_static_ImageReply_descriptor;
      }

      @java.lang.Override
      public Transform.ImageReply getDefaultInstanceForType() {
        return Transform.ImageReply.getDefaultInstance();
      }

      @java.lang.Override
      public Transform.ImageReply build() {
        Transform.ImageReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Transform.ImageReply buildPartial() {
        Transform.ImageReply result = new Transform.ImageReply(this);
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Transform.ImageReply) {
          return mergeFrom((Transform.ImageReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Transform.ImageReply other) {
        if (other == Transform.ImageReply.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                message_ = input.readStringRequireUtf8();

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 1;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImageReply)
    }

    // @@protoc_insertion_point(class_scope:ImageReply)
    private static final Transform.ImageReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Transform.ImageReply();
    }

    public static Transform.ImageReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImageReply>
        PARSER = new com.google.protobuf.AbstractParser<ImageReply>() {
      @java.lang.Override
      public ImageReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ImageReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImageReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Transform.ImageReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImageRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImageRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImageReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImageReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017transform.proto\"\260\001\n\014ImageRequest\022\r\n\005wi" +
      "dth\030\001 \001(\005\022\016\n\006height\030\002 \001(\005\022\r\n\005image\030\003 \001(\014" +
      "\022\014\n\004type\030\004 \001(\005\022\021\n\tpixelBits\030\005 \001(\005\022\025\n\rnum" +
      "Components\030\006 \001(\005\022\024\n\014transparency\030\007 \001(\005\022\020" +
      "\n\010hasalpah\030\010 \001(\010\022\022\n\nisalphapre\030\t \001(\010\"\035\n\n" +
      "ImageReply\022\017\n\007message\030\001 \001(\t23\n\007Greeter\022(" +
      "\n\010SayHello\022\r.ImageRequest\032\013.ImageReply\"\000" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ImageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImageRequest_descriptor,
        new java.lang.String[] { "Width", "Height", "Image", "Type", "PixelBits", "NumComponents", "Transparency", "Hasalpah", "Isalphapre", });
    internal_static_ImageReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ImageReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImageReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
